### ISSUE TITLE
Conditional SpectrumAutosave message formatting

### ISSUE THREAD

**Issue by EvilLord666** [Wissance/LabWatcher#13]
We should change behaviour of making autosave method, because we have 1 method for every notify (`ISpectrumReadyNotifier`),
this task could be solved using very complicated and abstractive approach, but we don't need it. It is better to solve this task as simple as it possible. If array of spectrum is empty we should form another message **for telegram only** ():
```
На {datetime} не было получено ни одного спектра, косвенно это может говорить об одной из следующих проблем:
* сбой работы спектрометрического оборудования / отключение управляющего компьютера;
* длительное отключение электроэнергии превышающее время работы системы от АКБ ;
* отсутствие сети (отключение роутера/мобильной сети интернет)
```

The simplest way is just making:
```csharp
if (specs.Any())
{
     // normal message
}
else 
{
    // make mentioned above message
}
```

**Comment by KarataevDmitry** [comment]
Yep, but I don't understand how to use markdown in telegram messages. According to docs it's possible (there's a parameter "format") but when I playing with first version of bot, I can't understood how I shall use it correctly

**Comment by EvilLord666** [comment]
To clarify about markdown i think it is not neccessary, issue done, code in `develop` branch, thanks @KarataevDmitry
